#!/usr/bin/env python
import numpy as np
import os


FN ='POSCAR'
FO = 'POSCAR_new'



from split import SPLIT

UU , LAT = SPLIT(FN)  



######---WRAPER---########
# DD is the XYZ matrix
# TT is wraping vector 
# LV is the LATTICE VECTOR 3by3 matrix 
Rx = 15
Ry = 9
Rz = 9
TT =np.matrix ([[Rx, Ry, Rz]])
def WRP(DD,TT,LV):
    for x in range (0,DD.shape[0]):
        if DD[x,0] > TT[0,0]: 
           DD[x,0] = DD[x,0] - LV[0,0] 
        if DD[x,1] > TT[0,1]:
           DD[x,1] = DD[x,1] - LV[1,1] 
        if DD[x,2] > TT[0,2]:
           DD[x,2] = DD[x,2] - LV[2,2] 
    return DD


OO = WRP(UU,TT,LAT)

FF = ZER(OO)


