#!/usr/bin/env python	
import numpy as np
import os


##########################################################################################
#######Splitting POSCAR into header and XYZ part #########################################
#function takes in POSCAR and halves it into XYZ part and rest.
# write both files to the current location as HH and TAIL and Return handle for 
# lattiec vectors and XYZ

def SPLIT(F_name):
    IN = open(F_name,'r')
    out = open('HH', 'w')
    for line in IN:
        if (line[0] == "D" or line[0] == "C" or line[0] == "c" or line[0] == "d"):
           out.write('CART\n')
           out.close()
           out = open('TAIL', 'w')
        else:
           out.write(line)
    out.close()
    IN.close()
    # getting handle for lattice vector and TAIL
    os.system("head -n5 HH | tail -n3  > LL")
    LAT =np.loadtxt('LL')
    os.system("awk '{print $1,$2,$3}' TAIL > TAIL_2") 
    os.system("mv TAIL_2 TAIL")
    UU = np.loadtxt('TAIL')
    os.system("rm -f LL TAIL")
    return (UU,LAT)


 

###########################################################################################
###########################################################################################


############################################################################################
###############################----ZERO-------##############################################

def ZER(OO):
     
    MM = OO.min(axis=0)

    OO[:,0] -= MM[0]

    OO[:,1] -= MM[1]

    OO[:,2] -= MM[2]

    return OO


############################################################################################
############################################################################################


##########################----DIRECT 2 CART------#############################

def D2C(AA,LL):
     
    AA[:,0] *= LL[0,0]
    AA[:,1] *= LL[1,1]
    AA[:,2] *= LL[2,2]

    return AA

################################################################################


UU , LAT = SPLIT('POSCAR')                                         # split POSCAR into HH and TAIL(coordinates part)
UU = D2C(UU,LAT)


######---WRAPER---########

Rx = 15
Ry = 9
Rz = 9
TT =np.matrix ([[Rx, Ry, Rz]])
def WRP(DD,TT,LV):
    for x in range (0,DD.shape[0]):
        if DD[x,0] > TT[0,0]: 
           DD[x,0] = DD[x,0] - LV[0,0] 
        if DD[x,1] > TT[0,1]:
           DD[x,1] = DD[x,1] - LV[1,1] 
        if DD[x,2] > TT[0,2]:
           DD[x,2] = DD[x,2] - LV[2,2] 
    return DD


OO = WRP(UU,TT,LAT)

FF = ZER(OO)



np.savetxt('FF', FF, delimiter=' ')     # X is an array
del UU
####mergin HH and FXYZ###############

#filenames = ['HH', 'FF']
#with open('POSCAR_fin', 'w') as outfile:
#    for fname in filenames:
#        with open(FF) as infile:
#            for line in infile:
#                outfile.write(line)

os.system("cat HH FF > POSCAR_fin")
os.system("rm HH FF" )
